language: python

python:
  - "3.9"
  - "pypy-5.3.1"

env:
  - TEST_RELEASE=false HYPER_FAST_PARSE=false
  - TEST_RELEASE=false HYPER_FAST_PARSE=true
  - TEST_RELEASE=true HYPER_FAST_PARSE=false
  - TEST_RELEASE=true HYPER_FAST_PARSE=true

matrix:
  allow_failures:
    - env: TEST_RELEASE=true HYPER_FAST_PARSE=true
    - env: TEST_RELEASE=true HYPER_FAST_PARSE=false

install:
  - ".travis/install.sh"
before_script: "flake8 hyper test"

script:
  - ".travis/run.sh"
