language: python

python:
  - "3.9"
  - "3.10"

env:
  - TEST_RELEASE=false HYPER_FAST_PARSE=false
  - TEST_RELEASE=false HYPER_FAST_PARSE=true
  - TEST_RELEASE=true HYPER_FAST_PARSE=false
  - TEST_RELEASE=true HYPER_FAST_PARSE=true

matrix:
  allow_failures:
    - env: TEST_RELEASE=true HYPER_FAST_PARSE=true
    - env: TEST_RELEASE=true HYPER_FAST_PARSE=false

install:
  - ".travis/install.sh"
before_script: "flake8 --max-complexity 15 --exclude 'hyper/packages/*' hyper test"

branches:
  only:
  - master
  - development

script:
  - >
      if [[ "$TEST_RELEASE" == true ]]; then
        py.test test_release.py
      else
        if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
          py.test test/
        else
          coverage run -m py.test test/
          coverage report
        fi
      fi
